# Generated by Django 4.2.4 on 2023-08-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_category_product_category_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
